version: '3'

services:
  backend:
    build: ./BackEnd  # Path to your backend Dockerfile
    ports:
      - "3030:3030"  # Map the backend's port to host port 8080

  frontend:
    build: ./FrontEnd  # Path to your frontend Dockerfile
    ports:
      - "3000:3000"  # Map the frontend's port to host port 3000
    depends_on:
      - backend
